name: PR Apply Download

on:
  issue_comment:
    types: [created]

jobs:
  download-artifact-on-apply:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/apply')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate unique name based on PR number
        id: generate
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          UNIQUE_NAME="pr-${PR_NUMBER}-$(openssl rand -hex 4)"
          echo "unique_name=${UNIQUE_NAME}.tfplan" >> "$GITHUB_OUTPUT"
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.generate.outputs.unique_name }}
          path: downloaded

      - name: Display contents of downloaded file
        run: |
          ls downloaded
          cat downloaded/"${{ steps.generate.outputs.unique_name }}".txt
